set(Kokkos_CXX_STANDARD "17")
set(${Kokkos_BACKEND_ARCH} ON)

if(CMAKE_BUILD_TYPE MATCHES "Debug")
    set(Kokkos_ENABLE_DEBUG ON CACHE STRING "Turn on Kokkos_Debug" FORCE)
    set(Kokkos_ENABLE_DEBUG_BOUNDS_CHE ON CACHE STRING "" FORCE)
    set(Kokkos_ENABLE_DEBUG_DUALVIEW_M ON CACHE STRING "" FORCE)
endif()